name: Auto Create PR

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        run: |
          PR_TITLE="Automated PR from ${GITHUB_REF#refs/heads/} to main"
          PR_BODY="This PR was created automatically by GitHub Actions. Changes made in commit ${GITHUB_SHA} by ${GITHUB_ACTOR}."
          
          BASE_BRANCH="main"
          HEAD_BRANCH="${GITHUB_REF#refs/heads/}"
          
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh pr create --base $BASE_BRANCH --head $HEAD_BRANCH --title "$PR_TITLE" --body "$PR_BODY"