name: Auto Create PR

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Check if PR exists
        id: pr-check
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          PR_EXISTS=$(gh pr list --base main --head ${GITHUB_REF#refs/heads/} --json number --jq 'length')
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
          unset GH_TOKEN

      - name: Create PR if not exists
        if: env.PR_EXISTS == '0'
        run: |
          PR_TITLE="PR from ${GITHUB_REF#refs/heads/} to main"
          PR_BODY="This PR was created automatically by GitHub Actions. Changes made in commit ${GITHUB_SHA} by ${GITHUB_ACTOR}."
          
          BASE_BRANCH="main"
          HEAD_BRANCH="${GITHUB_REF#refs/heads/}"
                    
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh pr create --base $BASE_BRANCH --head $HEAD_BRANCH --title "$PR_TITLE" --body "$PR_BODY"
          unset GH_TOKEN