name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Enable Corepack and use Yarn 4.2.2
      - name: Enable Corepack
        run: corepack enable

      - name: Use Yarn 4.2.2
        run: corepack prepare yarn@4.2.2 --activate

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: 'yarn'

      # Install dependencies with Yarn
      - run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4

      # Run affected tasks (lint, test, build)
      - run: yarn nx affected -t lint test build