name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Enable Corepack and use Yarn 4.2.2
      - name: Enable Corepack
        run: corepack enable

      - name: Use Yarn 4.2.2
        run: corepack prepare yarn@4.2.2 --activate

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - uses: nrwl/nx-set-shas@v4

      # Run affected tasks (lint, test, build)
      - run: yarn nx affected -t lint test build

      - name: Check if tag contains 'beta'
        id: check_tag
        run: |
          if [[ "${GITHUB_REF}" == *beta* ]]; then
            echo "This is a beta release."
            echo "is_beta=true" >> $GITHUB_ENV
          else
            echo "This is a stable release."
            echo "is_beta=false" >> $GITHUB_ENV
          fi

      # Publish packages depending on the tag
      - name: Publish packages
        run: |
          if [ "${{ env.is_beta }}" == "true" ]; then
            echo "Publishing beta version..."
            npx nx release publish --tag beta
          else
            echo "Publishing stable version..."
            npx nx release publish
          fi
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true